export type WireApi = "chat" | "responses";

export interface RenderProviderTomlInput {
  slug: string;
  providerLabel: string;
  baseUrl: string;
  model: string;
  wireApi: WireApi;
  /** When non-null, must be a flat string→string map. */
  requestHeaders: Record<string, string> | null;
}

function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function renderHttpHeaders(headers: Record<string, string>): string {
  const entries = Object.entries(headers).map(
    ([k, v]) => `${tomlString(k)} = ${tomlString(v)}`,
  );
  return `{ ${entries.join(", ")} }`;
}

export function renderProviderToml(input: RenderProviderTomlInput): string {
  const { slug, providerLabel, baseUrl, model, wireApi, requestHeaders } = input;
  const lines: string[] = [];
  lines.push("# Auto-generated by Paperclip codex-openai-compat adapter. Regenerated every run.");
  lines.push(`[model_providers.${slug}]`);
  lines.push(`name = ${tomlString(providerLabel)}`);
  lines.push(`base_url = ${tomlString(baseUrl)}`);
  lines.push(`env_key = "OPENAI_API_KEY"`);
  lines.push(`wire_api = ${tomlString(wireApi)}`);
  if (requestHeaders && Object.keys(requestHeaders).length > 0) {
    lines.push(`http_headers = ${renderHttpHeaders(requestHeaders)}`);
  }
  lines.push("");
  lines.push(`[profiles.${slug}]`);
  lines.push(`model_provider = ${tomlString(slug)}`);
  lines.push(`model = ${tomlString(model)}`);
  lines.push("");
  return lines.join("\n");
}
